//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_III_Dr4rum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Post_ID { get; set; }
        public string Topic_Tile { get; set; }
        public int Acc_ID { get; set; }
        public string Post_Info { get; set; }
        public int Like_Num { get; set; }
        public int Dislike_Num { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
